import type { MissionState } from "./types";

export const demoState: MissionState = {
  request: {
    id: "ER-2048",
    subjectId: "C-1842",
    subjectName: "Maya Chen",
    email: "maya.chen@erasegraph.example.test",
    purpose: "model_training",
    status: "pending",
    receivedAt: "2026-08-30T08:42:00.000Z",
    deadlineAt: "2026-09-29T08:42:00.000Z",
    verified: true,
  },
  systems: [
    {
      id: "postgres",
      name: "Customer Data Postgres",
      kind: "database",
      status: "connected",
      recordCount: 6,
      records: [
        {
          id: "pg-account-C1842",
          label: "Active customer account",
          category: "account",
          action: "retain",
          status: "found",
          reason: "Outside the model_training withdrawal scope.",
        },
        {
          id: "pg-training-profile-C1842",
          label: "Model-training profile",
          category: "training_profile",
          action: "delete",
          status: "found",
        },
        {
          id: "pg-embedding-C1842-001",
          label: "Training-text embedding row",
          category: "embedding",
          action: "delete",
          status: "found",
        },
        {
          id: "pg-consent-proof-C1842",
          label: "Consent history receipt",
          category: "consent_history",
          action: "retain",
          status: "found",
          reason: "Preserve the minimal consent-history record configured for audit evidence.",
        },
        {
          id: "pg-billing-C1842-2026-001",
          label: "Billing invoice record",
          category: "billing",
          action: "retain",
          status: "found",
          reason: "Preserve configured billing records; this is a demo policy, not legal advice.",
        },
        {
          id: "pg-legal-hold-C1842",
          label: "Configured legal-hold record",
          category: "legal",
          action: "retain",
          status: "found",
          reason: "Preserve records explicitly placed on the configured demo legal hold.",
        },
      ],
    },
    {
      id: "minio",
      name: "Training Artifacts MinIO",
      kind: "object_store",
      status: "connected",
      recordCount: 4,
      records: [
        {
          id: "subjects/C-1842/model-training/interview-audio.txt",
          label: "Synthetic interview audio placeholder",
          category: "training_audio",
          action: "delete",
          status: "found",
        },
        {
          id: "subjects/C-1842/model-training/interview-transcript.json",
          label: "Synthetic training transcript",
          category: "training_transcript",
          action: "delete",
          status: "found",
        },
        {
          id: "subjects/C-1842/billing/invoice-artifact.txt",
          label: "Billing invoice artifact",
          category: "billing",
          action: "retain",
          status: "found",
          reason: "Preserve configured billing records; this is a demo policy, not legal advice.",
        },
        {
          id: "subjects/C-1842/legal/hold-evidence.txt",
          label: "Configured hold evidence",
          category: "legal",
          action: "retain",
          status: "found",
          reason: "Preserve records explicitly placed on the configured demo legal hold.",
        },
      ],
    },
  ],
  plan: null,
  audit: [
    {
      id: "evt-intake",
      type: "demo_seeded",
      message: "Synthetic consent-withdrawal request and source records seeded.",
      createdAt: "2026-08-30T08:42:04.000Z",
      hash: "8b98c16a4aef",
    },
  ],
  verification: null,
};
